import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#fdf9f0',
        'surface-dim': '#dddad1',
        'surface-bright': '#fdf9f0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3ea',
        'surface-container': '#f1eee5',
        'surface-container-high': '#ece8df',
        'surface-container-highest': '#e6e2d9',
        'on-surface': '#1c1c16',
        'on-surface-variant': '#494640',
        'inverse-surface': '#31302b',
        'inverse-on-surface': '#f4f0e7',
        'outline': '#7a776f',
        'outline-variant': '#cbc6bd',
        'surface-tint': '#605e5b',
        'primary': '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1c1b19',
        'on-primary-container': '#868380',
        'inverse-primary': '#cac6c2',
        'secondary': '#795740',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed1b4',
        'on-secondary-container': '#795841',
        'tertiary': '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#281900',
        'on-tertiary-container': '#a87c2e',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fdf9f0',
        'on-background': '#1c1c16',
        'surface-variant': '#e6e2d9',
        'warm-ivory': '#F5F1E8',
        'deep-charcoal': '#171614',
        'earth-brown': '#6B4B35',
        'muted-ochre': '#B88A3B',
        'gold': '#D4AF37',
        'paper-white': '#FFFFFF',
        'accent-orange': '#E24C11',
      },
      fontFamily: {
        'display': ['EB Garamond', 'serif'],
        'headline': ['EB Garamond', 'serif'],
        'body': ['DM Sans', 'sans-serif'],
        'label': ['DM Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['84px', { lineHeight: '92px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-lg-mobile': ['48px', { lineHeight: '52px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '56px', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'body-lg': ['20px', { lineHeight: '32px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      spacing: {
        'unit': '8px',
        'gutter': '24px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'section-gap': '120px',
      },
      maxWidth: {
        'container': '1280px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
    },
  },
  plugins: [],
};

export default config;
